[project]
name="pcb-graph-of-parts"
version="0.0.1"
description="PCB vision built"
requires-python=">=3.9"
dependencies=["Pillow>=10.0.0"]


[build-system]
requires=["setuptools>=61.0"]
build-backend="setuptools.build_meta"
